INSERT ignore INTO Airline (AIRLINE_ID, UNIQUE_CARRIER, UNIQUE_CARRIER_NAME, UNIQUE_CARRIER_ENTITY)
SELECT DISTINCT 
    AIRLINE_ID, 
    UNIQUE_CARRIER,
    UNIQUE_CARRIER_NAME,
    UNIQUE_CARRIER_ENTITY
FROM Master_Meta_Data
WHERE AIRLINE_ID IS NOT NULL;    
    
Select count(distinct Airline_id) from Airline;    

-- ORIGIN Airports
INSERT INTO Airport (AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT_CODE, CITY_NAME,
					STATE_ABR, STATE_FIPS, STATE_NM, WAC)
SELECT DISTINCT 
     ORIGIN_AIRPORT_ID,
     ORIGIN_AIRPORT_SEQ_ID,
     ORIGIN_CITY_MARKET_ID,
     ORIGIN,
     ORIGIN_CITY_NAME,
     ORIGIN_STATE_ABR,
     ORIGIN_STATE_FIPS,
     ORIGIN_STATE_NM,
     ORIGIN_WAC
FROM master_meta_data;   


-- DEST Airports
INSERT INTO Airport (AIRPORT_ID, AIRPORT_SEQ_ID, CITY_MARKET_ID, AIRPORT_CODE, CITY_NAME,
					STATE_ABR, STATE_FIPS, STATE_NM, WAC) 
SELECT DISTINCT 
	DEST_AIRPORT_ID,
    DEST_AIRPORT_SEQ_ID,
    DEST_CITY_MARKET_ID,
    DEST,
    DEST_CITY_NAME,
    DEST_STATE_ABR,
    DEST_STATE_FIPS,
    DEST_STATE_NM,
    DEST_WAC
FROM master_meta_data
WHERE DEST_AIRPORT_ID NOT IN (  
	SELECT AIRPORT_ID FROM Airport
);
 
select * from Airport;    

INSERT INTO Flight (AIRLINE_ID, ORIGIN_AIRPORT_ID, DEST_AIRPORT_ID, DISTANCE,
                     DISTANCE_GROUP, YEAR, QUARTER, MONTH, CLASS)
SELECT
      AIRLINE_ID,
      ORIGIN_AIRPORT_ID,
      DEST_AIRPORT_ID,
      DISTANCE,
      DISTANCE_GROUP,
      YEAR,
      QUARTER,
      MONTH,
      CLASS
FROM master_meta_data;      

select * from Flight; 



INSERT INTO FlightMetrics (
    FLIGHT_ID, PASSENGERS, FREIGHT, MAIL
)
SELECT
    f.FLIGHT_ID,
    MAX(m.PASSENGERS),
    MAX(CAST(NULLIF(m.FREIGHT, '') AS DECIMAL(10,2))) AS FREIGHT,
    MAX(m.MAIL)
FROM master_meta_data m
JOIN Flight f
  ON f.AIRLINE_ID = m.AIRLINE_ID
 AND f.ORIGIN_AIRPORT_ID = m.ORIGIN_AIRPORT_ID
 AND f.DEST_AIRPORT_ID = m.DEST_AIRPORT_ID
 AND f.YEAR = m.YEAR
 AND f.MONTH = m.MONTH
 AND f.QUARTER = m.QUARTER
 AND f.DISTANCE = m.DISTANCE
LEFT JOIN FlightMetrics fm 
  ON f.FLIGHT_ID = fm.FLIGHT_ID
WHERE fm.FLIGHT_ID IS NULL
GROUP BY f.FLIGHT_ID;

select * from flightmetrics;

    
INSERT INTO CITY (CITYNAME, STATE_ABR, STATE_NM)
SELECT DISTINCT
	ORIGIN_CITY_NAME,
	ORIGIN_STATE_ABR,
	ORIGIN_STATE_NM
FROM master_meta_data;  

describe city;  
select * from city;

INSERT INTO CITY (CITYNAME, STATE_ABR, STATE_NM)
SELECT DISTINCT 
     DEST_CITY_NAME,
     DEST_STATE_ABR,
     DEST_STATE_NM
FROM master_meta_data     
WHERE DEST_CITY_NAME NOT IN (
	SELECT CITYNAME FROM City
); 

select * from city;


















